rxnsToRemove = {'ACTNdiff', 'ALOX','3HPPt','EXC_BOTH_3hpp_e',...
    'ACALDt','AACPS4','AACPS5','AACPS182','NH4DISex','Cuabc','RBLK2',...
    'DIACTt','EXC_BOTH_diact_e','EXC_BOTH_m_0005','EXC_BOTH_fe2_e',...
    'tr_fe2','FORt','PYRt2','SUCCt2r','EXC_BOTH_k_e',...
    'EXC_BOTH_Levan','EXC_BOTH_mg2_e','EXC_BOTH_mn2_e','EXC_BOTH_m_0007',...
    'FA181tr','EXC_BOTH_pyr_e','EXC_BOTH_na1_e','EXC_BOTH_succ_e',...
    'EXC_BOTH_so4_e','EXC_BOTH_actn__R_e','EXC_BOTH_acald_e',...
    'EXC_BOTH_drib_e','EXC_BOTH_dha_e','EXC_BOTH_glyb_e',...
    'HISTAap','EXC_BOTH_ptrc_e'};

remodel_AC5 = removeReactions(omiModel,rxnsToRemove,true,...
            true,true);
omiModelr=setParam(remodel_AC5,'lb',{'EXC_BOTH_pro__L_e'},[0]);
solomiModel = solveLP(omiModelr,1);
fprintf(['umax omiModel = ' num2str(solomiModel.f*-1) ' per hour' '\n']);
